### PR TITLE
Linking tirific against giza instead of pgplot5

### LINKED ISSUE #203: does tirific need to depend on pgplot5 or can it use giza?
Pgplot has been end-of-lined and replaced by giza on modern Ubuntus. Unfortunately, one can't install both libpgplot5 and giza, they seem to be mutually exclusive.

Can we try linking tirific against giza instead of pgplot5 (i.e. install libgiza-dev for the build)? I believe it's a drop-in replacement.

### PR DESCRIPTION
**Pull request by Athanaseus**
resolves https://github.com/kernsuite/packaging/issues/203

### CODE REVIEW

**Comment by gijzelaerr** [comment]
can you force it to link to the giza package by the configure script? Or does giza install a backwards compatible pgplot lib with that same name?

**Comment by Athanaseus** [comment]
Included with giza are PGPLOT interfaces that aim to replicate the full public interface to PGPLOT. This means that giza can be compiled as a drop-in replacement for libpgplot and libcpgplot. So older programs written using PGPLOT can be linked against giza with the source code unchanged.

**Comment by Athanaseus** [comment]
Also see https://github.com/sabourke/ppgplot/issues/1

**Comment by Athanaseus** [comment]
But I get the following when I test run.

```L:4/4 I:36/5.0E+06 M:08/5.0E+06/351 P:CONDISP R:01 A:-5.6E-02/+2.0E-02 N:2.8E+06/2.8E+06 F:+1.9E+01/+1.9E+01 C:6.4012567E+05 S:+1.8E+308
L:4/4 I:36/5.0E+06 M:09/5.0E+06/352 P:CONDISP R:01 A:+3.4E-02/+2.0E-02 N:2.8E+06/2.8E+06 F:+1.9E+01/+1.9E+01 C:6.4012496E+05 S:+1.8E+308
L:4/4 I:36/5.0E+06 M:10/5.0E+06/353 P:CONDISP R:01 A:+2.1E-02/+2.0E-02 N:2.8E+06/2.8E+06 F:+1.9E+01/+1.9E+01 C:6.4012505E+05 S:+1.8E+308
L:4/4 I:36/5.0E+06 M:11/5.0E+06/354 P:CONDISP R:01 A:-1.3E-02/+2.0E-02 N:2.8E+06/2.8E+06 F:+1.9E+01/+1.9E+01 C:6.401E+05 S:+4.2E+01
Finished N:2811414/2811978 F:1.85E+01/1.85E+01 C:6.401250E+05  S:4.222912E+01
%giza - ERROR - giza_open_device: Unknown device, device not opened
Segmentation fault
```

**Comment by gijzelaerr** [comment]
see if you can get a stack trace and report it at the giza issue tracker, please.

* Install debugging symbols package if available for related packages
* Compile tirific with debug symbols enabled
* Run tirific in a debugger like gdb and lldb, see where it crashes
* report bug upstream.

**Comment by Athanaseus** [comment]
I got this to work now with the latest release without any hurdles. The previous, version required device to be set to `pdf`. The default parameter file for `tirific` used **vcps**.

`Giza` supported the following devices:

? : | User selects device
-- | --
/xw : | X-window
/eps : | Encapsulated Postscript
/png : | Portable Network Graphics file
/svg : | Scalable Vector Graphics file
/pdf : | Portable Document Format
/vpdf : | Landscape Portable Document Format
/ps : | PostScript
/vps : | Landscape Postscript

PGPLOT graphics or hardcopy device  used:

? : | User selects device
-- | --
/xs : | This is a re-sizable and persistent X window.
/xw : | This is a transient X window.
/xd : | This is the pgdisp X windows server (deprecated).
/ps : | Postscript. PGPLOT will write the plot as a disk file in postscript form. At ATNF sites, you can print this postscript file with the command: % lp filename
/vps : | Vertical postscript. The only difference between this and ps, is that vps generates a plot in portrait mode, whereas ps is in landscape mode.
/cps : | Colour postscript in landscape mode.
/vcps : | Colour postscript in portrait mode.
/null : | The null device. Useful for debugging when you do not have a display.
/re : | A VT100 with RETROgraphics card.
/v603 : | A V603 terminal.
/krm3 : | A Kermit 3 IBM-PC terminal emulator.
/tek : | A TEK 4010 compatible terminal (or window).

**Comment by Athanaseus** [comment]
This is the output from the run:

Screenshot from 2019-10-31 16-32-19

**Pull request merged**
